version: '3'

services:

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier

  dragg:
    build: .
    environment:
    - REDIS_HOST=redis
    - localhost=6397
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
