
name: Run Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Local Build
      run: |
        pip install -e .
    - name: Unit Tests
      run: |
        cd testing
        python test_submission.py